### PR TITLE
Add .NET 5.0 support

### PR DESCRIPTION
**Pull request by pjanotti**
Initial work to add .NET 5.0: currently validated Windows locally. Starting to test CI and Linux.

### CODE REVIEW

**Review by dszmigielski — APPROVED** [review]
I have tested this with `dotnet new webapi` application with 2 additional http calls addid in the controller - one executed using `HttpClient` (`HttpMessageHandler`), the second one using `WebRequest`. Seems to be working fine!
tests

**Comment by pjanotti** [comment]
Thanks for checking @dszmigielski

**Review by pellared — APPROVED** [review]
:shipit:

**Comment by pellared** [comment]
@pjanotti Looks better. Some tests failed: https://dev.azure.com/signalfx/signalfx-dotnet-tracing/_build/results?buildId=5567&view=logs&jobId=97a617bf-bcbd-5dfa-bba2-cfba2747b693&j=97a617bf-bcbd-5dfa-bba2-cfba2747b693&t=896bae44-395a-53fa-1a63-8aa1f3fdb150

**Comment by pjanotti** [comment]
Yeah, we started to get these `System.BadImageFormatException` that's why I started to try all these changes on the Windows integration tests. At least now they are running the correct x86/x64 tests but I have to investigate the failures. At least now they seem consistent. Plus a flaky test on Windows: 
```
2021-06-24T17:01:40.9414137Z   Failed Datadog.Trace.OpenTracing.Tests.OpenTracingSpanTests.Finish_EndTimeInThePast_DurationIs0 [1 ms]
2021-06-24T17:01:40.9417099Z   Error Message:
2021-06-24T17:01:40.9418406Z    System.NullReferenceException : Object reference not set to an instance of an object.
2021-06-24T17:01:40.9419874Z   Stack Trace:
2021-06-24T17:01:40.9420813Z      at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
2021-06-24T17:01:40.9421872Z    at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
2021-06-24T17:01:40.9422991Z    at Castle.DynamicProxy.ModuleScope.GetFromCache(CacheKey key)
2021-06-24T17:01:40.9425025Z    at Castle.DynamicProxy.Generators.BaseProxyGenerator.GetFromCache(CacheKey key)
2021-06-24T17:01:40.9427383Z    at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory)
2021-06-24T17:01:40.9428722Z    at Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.GenerateCode(Type proxyTargetType, Type[] interfaces, ProxyGenerationOptions options)
2021-06-24T17:01:40.9430287Z    at Castle.DynamicProxy.DefaultProxyBuilder.CreateInterfaceProxyTypeWithoutTarget(Type interfaceToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
2021-06-24T17:01:40.9432969Z    at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyTypeWithoutTarget(Type interfaceToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
2021-06-24T17:01:40.9434655Z    at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget(Type interfaceToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, IInterceptor[] interceptors)
2021-06-24T17:01:40.9436264Z    at Moq.CastleProxyFactory.CreateProxy(Type mockType, IInterceptor interceptor, Type[] interfaces, Object[] arguments)
2021-06-24T17:01:40.9437597Z    at Moq.Mock`1.InitializeInstancePexProtected()
2021-06-24T17:01:40.9438507Z    at Moq.PexProtector.Invoke(Action action)
2021-06-24T17:01:40.9440537Z    at Moq.Mock`1.InitializeInstance()
2021-06-24T17:01:40.9441676Z    at Moq.Mock`1.OnGetObject()
2021-06-24T17:01:40.9442498Z    at Moq.Mock.get_Object()
2021-06-24T17:01:40.9443285Z    at Moq.Mock`1.get_Object()
2021-06-24T17:01:40.9444568Z    at Datadog.Trace.OpenTracing.Tests.OpenTracingSpanTests..ctor() in D:\a\1\s\test\Datadog.Trace.OpenTracing.Tests\OpenTracingSpanTests.cs:line 27
2021-06-24T17:01:41.0409474Z Results File: D:\a\_temp\VssAdministrator_WIN-4MOHR744TQ5_2021-06-24_17_01_40.trx
```

**Pull request merged**
