### PR TITLE
Rename Managed Modules

### PR DESCRIPTION
**Pull request by pjanotti**
1. SignalFx.Tracing.ClrProfiler.Managed

Remaining still pending...

### CODE REVIEW

**Comment by pjanotti** [comment]
@rmfitzpatrick this is still WIP but I think it will be easier to review as each rename comes.

**Comment by pjanotti** [comment]
WIP but easier to review rename of each file separately

**Comment by rmfitzpatrick** [comment]
This lgtm but I wonder about the full ci workflow not running?

**Comment by pjanotti** [comment]
> This lgtm but I wonder about the full ci workflow not running?

This seems something related to Azure Pipelines reporting, I've seen the similar in OTel .NET and the results for the others are there but it seems that they are collapsed. Anyway, I will do a pass on all the failures to confirm that they are not caused by the changes.

**Comment by pjanotti** [comment]
Many of the failures are related to metrics and some other seem intermittent failures.

**Comment by pjanotti** [comment]
Test failures don't seem related to the changes, merging.

**Pull request merged**
