### PR TITLE
Fix RabbitMq delivery mode tags

### PR DESCRIPTION
**Pull request by RassK**
(bug) RabbitMq delivery mode tags got swapped with RouteKey, which caused duplicate tags and crashed client application.

### CODE REVIEW

**Comment by pellared** [comment]
Why/How was it crashing? Can a tag be duplicated? Is it not a simple dictionary so the new value is replacing the old one?

**Comment by RassK** [comment]
> Why and how was it crashing? Can a tag be duplicated? Is it not a simple dictionary so the new value is replacing the old one?

main branch has old simplified tag model, just a common dictionary.

**Review by pellared — APPROVED** [review]
I see. Thanks

SIde note. Maybe it is better to use `tags[key] = ...` instead of `tags.Add(key, ...` to minimize the chance of throwing an exception and have probably a little better performance.

**Comment by pjanotti** [comment]
> Actually it should not have been the client's app that crashed but our integration tests.

@RassK can we add such a test or is it the cost too high?

**Pull request merged**
