### PR TITLE
Fix ci

### PR DESCRIPTION
**Pull request by pjanotti**
## Why

Fix CI: failing Linux container integration tests for various reasons, with chief reason being lack of space. This likely broke with the upgrade of the GH runner. 

## What

* Removed dotnet 5.0 from build.
* Removed dotnet install for SDK 3.0 and 5.0 on Linux container tests
* Removed docker images and files to get space on the runner
* Removed Lambda tests (and related images) since they were taking too much space.

## Tests

N/A

### CODE REVIEW

**Comment by Kielek** [comment]
I do not understand why you are removing .NET5 from the pipeline. We still have _limited_ support for this.

**Comment by pjanotti** [comment]
> I do not understand why you are removing .NET5 from the pipeline. We still have limited support for this.

It was the best TFM to be removed - I wanted to remove one for the space issues. .NET 5.0 was a good candidate because, it was since its release, known as a non-LTS. This makes its less likely that there is still some one using it. Removing .NET Core 2.1 is riskier since it is targeted in the product build itself. If you look where .NET 5.0 was removed in CI it is just from tests, not product build.

**Review by Kielek — APPROVED** [review]
Thanks for clarification.
Please remove required steps related to .NET 5. Then we should be fine to merge.

**Comment by pjanotti** [comment]
> remove required steps related to .NET 5

@Kielek I removed a few references to .NET 5 from dev docs, see [dc6692a](https://github.com/signalfx/signalfx-dotnet-tracing/pull/742/commits/dc6692a70469b659e51a0e8635217b7151bec0b8), let me know if you have something else on your mind. There are other mentions to net5.0, but, in general they aren't for relevant in this context.

**Comment by pjanotti** [comment]
It seems that tests that use SQL are flaky:

* https://github.com/signalfx/signalfx-dotnet-tracing/actions/runs/6564559492/job/17831168347#step:6:10024
* https://github.com/signalfx/signalfx-dotnet-tracing/actions/runs/6564559492/job/17831169006#step:6:10621
* https://github.com/signalfx/signalfx-dotnet-tracing/actions/runs/6564559492/job/17831170300#step:6:10658
* https://github.com/signalfx/signalfx-dotnet-tracing/actions/runs/6564559492/job/17831170506#step:6:9282

Re-run...

**Comment by pjanotti** [comment]
Two tests that seem specially flaky:

https://github.com/signalfx/signalfx-dotnet-tracing/actions/runs/6564559492/job/17833189041?pr=742#step:6:9299

**Pull request merged**
